export {default as ContainerLogin} from "./ContainerLogin";
export {default as ContenedorPerfil} from "./ContenedorPerfil";
export {default as MenuDesktop} from "./MenuDesktop";
export {default as MenuCabeceraDesktop} from "./MenuCabeceraDesktop";
export {default as Welcome} from "./Welcome";
export {default as ImgFase2} from "./ImgFase2";
export {default as CardsInfoGeneral} from "./CardsInfoGeneral";
export {default as Table} from "./Table";
export {default as BasicTable} from "./BasicTable";
export {default as MatchTableOptions} from "./MatchTableOptions";
export {default as NewStudent} from './NewStudent';
export {default as MenuResponsive} from "./MenuResponsive";
export {default as MenuResponsiveCabecera} from "./MenuResponsiveCabecera";
export {default as NewMentor} from './NewMentor'
export {default as TableMatch} from './TableMatch'
